spring.application.name=eventportal

#Database connnection

spring.datasource.url=jdbc:mysql://localhost:3306/event_portal
spring.datasource.username=${DB_UserName}
spring.datasource.password=${DB_Password}


#spring console configuration

spring.main.banner-mode=false

#spring server configuration

server.servlet.context-path=/api/v1

#spring security config
spring.security.user.name=username
spring.security.user.password=12345678

#openAPI Swagger UI
springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/docs.html

#javamail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${Email_ID}
spring.mail.password=${App_Password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true